In [1]:
import theano
import theano.tensor as tt
import numpy as np

In [2]:
X = tt.matrix('X')
W = tt.matrix('W')
b_sym = tt.vector('b_sym')

In [3]:
def myfunc(v):
    return tt.tanh(tt.dot(v, W)+b_sym)
results, _ = theano.scan(myfunc, sequences=X)
compute_elementwise = theano.function(inputs=[X, W, b_sym], outputs=results)

In [6]:
results, updates = theano.scan(lambda v: tt.tanh(tt.dot(v, W) + b_sym), sequences=X)
compute_elementwise = theano.function(inputs=[X, W, b_sym], outputs=results)

In [4]:
x= np.eye(2, dtype=theano.config.floatX)
w = np.ones((2, 2), dtype=theano.config.floatX)
b = np.ones((2), dtype=theano.config.floatX)
b[1] = 2

In [5]:
print(compute_elementwise(x, w, b))

[[ 0.96402758  0.99505475]
 [ 0.96402758  0.99505475]]


In [29]:
print(compute_elementwise(x, w, b))

[[ 0.96402758  0.99505475]
 [ 0.96402758  0.99505475]]


In [11]:
print(np.tanh(x.dot(w)+b))

[[ 0.96402758  0.99505475]
 [ 0.96402758  0.99505475]]



 Computing the sequence x(t) = tanh(x(t - 1).dot(W) +p(T - t).dot(V))




In [13]:
X = tt.vector("X")
W = tt.matrix("W")
P = tt.matrix("P")
V = tt.matrix("V")

In [21]:
results, _ = theano.scan(lambda p, x_tm1: tt.tanh(tt.dot(x_tm1, W) + tt.dot(p, V)),
                         sequences=[P[::-1]], outputs_info=[X]
                        )

In [22]:
compute_seq = theano.function(inputs=[X, W,P,V], outputs=results)

In [23]:
x = np.zeros((2), dtype=theano.config.floatX)
x[1] = 1
w = np.ones((2, 2), dtype=theano.config.floatX)
p = np.ones((5, 2), dtype=theano.config.floatX)
p[0, :] = 3
v = np.ones((2, 2), dtype=theano.config.floatX)

In [24]:
compute_seq(x, w, p, v)

array([[ 0.99505475,  0.99505475],
       [ 0.99931591,  0.99931591],
       [ 0.99932746,  0.99932746],
       [ 0.99932749,  0.99932749],
       [ 0.99999977,  0.99999977]])

Scan Example: Computing the sequence x(t) = x(t - 1).dot(U) + x(t - 2).dot(V)

In [32]:
X = tt.vector("X")
U = tt.matrix("U")
V = tt.matrix("V")
n_sym = tt.iscalar('n_sym')

In [59]:
results, _ = theano.scan(lambda x_tm1, x_tm2: x_tm1 + x_tm2,
                        n_steps=n_sym, outputs_info=[dict(initial=X, 
                                                          taps=list(-1 * np.arange(1, 3)))])
compute_seq2 = theano.function(inputs=[X, n_sym], outputs=results)

In [64]:
x = np.zeros(30)
#x[1] = 1
x[1] = 1
n = 10

In [66]:
compute_seq2(x, n)

array([  1.,   2.,   3.,   5.,   8.,  13.,  21.,  34.,  55.,  89.])